apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ryansaad/online-boutique-gitops.git
    targetRevision: HEAD
    path: kustomize/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true