apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: frontend
    newName: 861276082757.dkr.ecr.us-east-1.amazonaws.com/online-boutique/frontend
    newTag: latest